config/routes.rb
HortwithmshV2::Application.routes.draw do
  resources :subjects
  resources :hydroponics_data
  resources :materials

  resources :classrooms do
    post 'edit'
    post 'add_unit'
    post 'delete'
  end

  resources :materials do
    post 'delete'
    post 'edit_name'
  end

  resources :units do
    post 'delete'
  end

  match 'hydroponics_data/csv/:filter' => 'hydroponics_data#download'

  post 'classrooms/sort' => 'classrooms#sort'

  match 'classes/:name' => 'main#classroom'
  match 'classes/:class_name/files/:file_name' => 'main#download'

  match 'plant_science' => 'main#plant_science'
  match 'plant_science_ii' => 'main#plant_science_ii'
  match 'floral_design' => 'main#floral_design'
  match 'career_choices' => 'main#career_choices'

  match 'about' => 'main#about'
  match 'ffa' => 'main#ffa'
  match 'stem' => 'main#stem'
  match 'plant-sale' => 'main#plant_sale'

  match 'mobile' => 'mobile#index'
  post 'mobile/post-plant-data' => 'mobile#post_plant_data'
  post 'mobile/get-plant-information' => 'mobile#get_plant_information'

  root :to => 'main#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  has_many :classroom_units
  has_many :units, :through => :classroom_units
  has_one :subject, :primary_key => :subject_id, :foreign_key => :id

  default_scope order("sort asc")

  def self.all_sorted
    Classroom.find(:all, :order => 'sort asc')
  end

  def self.find_by_url(path)
    Classroom.find(:first, :conditions => ["lower(name) = ?", path.gsub('-',' ')])
  end

  def name_url
    return name.downcase.gsub(' ','-')
  end

  def html_description
    return self.description.html_safe
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_filter :authenticate

  def index
    @classrooms = Classroom.all_sorted
  end

  def create
    @classroom = Classroom.create(:name => params[:class_name])
    @classroom.save
    classrooms = render_to_string(:partial => 'index_classroom', :collection => Classroom.all_sorted)

    respond_to do |format|
      format.js { @classrooms = classrooms }
    end
  end

  def edit
    classroom = Classroom.find(params[:classroom_id])
    
    classroom.update_attributes(params[:classroom])
    
    respond_to do |format|
      format.js { @results = {:message => 'Classroom details updated.', :classroom => classroom} }
    end
  end

  def add_unit
    classroom = Classroom.find(params[:classroom_id])

    if !params[:unit][:id].empty?
      unit = Unit.find(params[:unit][:id])
    else
      unit = Unit.create(:name => params[:name])
    end

    classroom.units << unit
    classroom.save

    units_html = render_to_string(:partial => 'units/index_unit', :collection => classroom.units, :layout => false)

    respond_to do |format|
      format.js { @results = {:message => 'Unit added to classroom.', :classroom => classroom, :units => units_html} }
    end
  end

  def show
    @classroom = Classroom.find(params[:id])
    @all_units = Unit.find(:all)
  end

  def delete
    classroom = Classroom.find(params[:classroom_id])
    classroom.delete
    classrooms_html = render_to_string(:partial => 'classrooms/index_classroom', :collection => Classroom.all_sorted, :layout => false)

    respond_to do |format|
      format.js { @results = {:message => 'Classrooms updated.', :classrooms => classrooms_html} }
    end
  end

  def sort
    params[:list].each_with_index do |item, index|
      case (params[:type])
        when 'classrooms'
          sortable_object = Classroom.find(item.to_i)
          print 'classrooms'
        when 'materials'
          sortable_object = Material.find(item.to_i)
          print 'materials'
        when 'units'
          sortable_object = Unit.find(item.to_i)
          print 'units'
      end
      sortable_object.sort = index
      sortable_object.save
    end
    render :nothing => true
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
  def nav_link(name, path)
    isActive = request.path.include?(path)
    className = isActive ? 'active' : ''
    content_tag(:li, :class => className) do
      link_to name, path
    end
  end
end

app/views/classrooms/_index_classroom.html.haml
.row.index_classroom{'data-id' => index_classroom.id}
  .span9.class_info
    %span 
      = index_classroom.name
  .span3.actions
    %a.btn{:href => classroom_path(index_classroom) } Edit
    // %a.btn Disable
    = link_to('Delete', (classroom_path(index_classroom) + '/delete'), :remote => true, :method => 'post', :confirm => "Are you sure you want to delete #{index_classroom.name}?", :class => 'btn btn-danger')
    //%a.btn.btn-danger{:href => } Delete

app/views/classrooms/add_unit.js.erb
Alert.show('<%=escape_javascript(@results[:message])%>');
$('#units').html($("<%=escape_javascript(raw(@results[:units]))%>"));
$('#add_unit').modal('hide')

app/views/classrooms/create.js.erb
$('#classrooms').html("<%= escape_javascript(raw(@classrooms)) %>");
$('.modal').modal('hide');

app/views/classrooms/delete.js.erb
Alert.show('<%=escape_javascript(@results[:message])%>');
$('#classrooms').html($("<%=escape_javascript(raw(@results[:classrooms].strip))%>"));

app/views/classrooms/edit.js.erb
Alert.show('<%=escape_javascript(@results[:message])%>');
$('h1').html('<%=escape_javascript(@results[:classroom].name)%>');

app/views/classrooms/index.html.haml
%h1 Classes

#classrooms.sortable
  = render :partial => 'index_classroom', :collection => @classrooms

%button{:class => 'btn-primary btn-large', 'data-toggle' => 'modal', :href => '#new_class'}
  %i{:class => 'icon-plus icon-white'}
  Create New Class

#new_class.modal.hide.fade.in
  .modal-header
    %a.close{'data-dismiss' => 'modal'} x
    %h3 Enter a name for this class:
  .modal-body
    = form_tag classrooms_path, :remote => true, :id => 'create_classroom_form', :update => 'classrooms' do
      %input#class_name{:name => 'class_name'}
  .modal-footer
    %a{:href => '#', :class => 'btn btn-primary', :id => 'create_classroom_button'} Create
    %a{:href => '#', :class => 'btn', 'data-dismiss' => 'modal'} Cancel

app/views/classrooms/show.html.haml
- content_for(:breadcrumb) do
  %li
    %span.divider= '/'
    = @classroom.name

%h1= @classroom.name

= form_tag edit_classroom_path(@classroom), :remote => true, :id => 'classroom_form' do
  %label{:for => 'name'} Name
  %input{:class => 'span6', :name => 'classroom[name]', :id => 'classroom[name]', :value => @classroom.name}
  %br
  &nbsp;
  %label{:for => 'introduction'} Intro Header
  %textarea{:class => 'span6', :name => 'classroom[introduction]', :id => 'classroom[introduction]', :value => @classroom.introduction}
    = @classroom.introduction
  %label{:for => 'description'} Description
  %textarea{:class => 'span6', :name => 'classroom[description]', :id => 'classroom[description]', :value => @classroom.description}
    = @classroom.description
  / %label{:for => 'name'} Subject
  / = select('classroom', 'subject_id', Subject.all.collect {|s| [s.name, s.id]}, {:include_blank => true})

%button{:class => 'btn btn-primary', :id => 'save_changes'} Save Changes 
%br
&nbsp;

%h2 Units

#units.sortable
  = render :partial => 'units/index_unit', :collection => @classroom.units

%button{:class => 'btn btn-primary', :id => 'add_unit_button', 'data-toggle' => 'modal', :href => '#add_unit'} 
  %i{:class => 'icon-plus icon-white'}
  Add Unit

#add_unit.modal.hide.fade.in
  .modal-header
    %a.close{'data-dismiss' => 'modal'} x
    %h3 Enter a name for this unit or choose an existing one:
  .modal-body
    = form_tag classroom_path(@classroom) + '/add_unit/', :remote => true, :id => 'add_unit_form' do
      %label Existing Units
      = select('unit', 'id', @all_units.collect {|s| [s.name, s.id]}, {:include_blank => true})
      %label New Unit
      %input#unit_name{:name => 'name'}
  .modal-footer
    %a{:href => '#', :class => 'btn btn-primary', :id => 'add_unit_submit_button'} Add
    %a{:href => '#', :class => 'btn', 'data-dismiss' => 'modal'} Cancel