config/routes.rb
HortwithmshV2::Application.routes.draw do
  resources :subjects
  resources :hydroponics_data
  resources :materials

  resources :classrooms do
    post 'edit'
    post 'add_unit'
    post 'delete'
  end

  resources :materials do
    post 'delete'
    post 'edit_name'
  end

  resources :units do
    post 'delete'
  end

  match 'hydroponics_data/csv/:filter' => 'hydroponics_data#download'

  post 'classrooms/sort' => 'classrooms#sort'

  match 'classes/:name' => 'main#classroom'
  match 'classes/:class_name/files/:file_name' => 'main#download'

  match 'plant_science' => 'main#plant_science'
  match 'plant_science_ii' => 'main#plant_science_ii'
  match 'floral_design' => 'main#floral_design'
  match 'career_choices' => 'main#career_choices'

  match 'about' => 'main#about'
  match 'ffa' => 'main#ffa'
  match 'stem' => 'main#stem'
  match 'plant-sale' => 'main#plant_sale'

  match 'mobile' => 'mobile#index'
  post 'mobile/post-plant-data' => 'mobile#post_plant_data'
  post 'mobile/get-plant-information' => 'mobile#get_plant_information'

  root :to => 'main#index'

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :classroom_units
  has_many :classrooms, :through => :classroom_units
  has_many :materials

  default_scope order("sort asc")
end

app/controllers/units_controller.rb
class UnitsController < ClassroomsController
  before_filter :authenticate

  def index
    @units = Unit.all
  end

  def show
    @unit = Unit.find(params[:id])
    @materials = @unit.materials
  end

  def delete
    unit = Unit.find(params[:unit_id])
    classroom = unit.classrooms.first

    unit.classrooms.each do |classroom|
      classroom.units.delete(unit)
    end

    if classroom
      units_modified = classroom.units
    else
      units_modified = Unit.find(:all)
    end

    unit.materials.each do |material|
      material.delete_file
      material.delete
    end

    unit.delete

    units_html = render_to_string(:partial => 'units/index_unit', :collection => units_modified, :layout => false)

    respond_to do |format|
      format.js { @results = {:message => 'Unit removed.', :units => units_html} }
    end
  end
end

app/views/units/_index_unit.html.haml
.row.index_unit{'data-id' => index_unit.id}
  .span9.unit_info
    %span 
      = index_unit.name
  .span3.actions
    %a.btn{:href => unit_path(index_unit) } Edit
    //%a.btn Disable
    = link_to('Delete', (unit_path(index_unit) + '/delete'), :remote => true, :method => 'post', :confirm => "Are you sure you want to delete #{index_unit.name}?", :class => 'btn btn-danger')

app/views/units/delete.js.erb
Alert.show('<%=escape_javascript(@results[:message])%>');
$('#units').html($("<%=escape_javascript(raw(@results[:units].strip))%>"));

app/views/units/index.html.haml
%h1 Units

#units
  = render :partial => 'index_unit', :collection => @units

app/views/units/show.html.haml
%h3 Manage Unit Materials
%h1= @unit.name

#materials.sortable
  = render :partial => 'materials/index_material', :collection => @materials

%button{:class => 'btn-primary btn-large', 'data-toggle' => 'modal', :href => '#new_material'}
  %i{:class => 'icon-plus icon-white'}
  Add New Material

%button{:class => 'btn-primary btn-large', 'data-toggle' => 'modal', :href => '#new_material_link'}
  %i{:class => 'icon-plus icon-white'}
  Add New Link

#new_material.modal.hide.fade.in
  .modal-header
    %a.close{'data-dismiss' => 'modal'} x
    %h3 New Document:
  .modal-body
    = form_tag materials_path, :remote => true, :multipart => true, :class => 'material_form', :id => 'material_form' do
      %label Name
      %input{:name => 'material[name]'}
      %input{:type => 'hidden', :name => 'unit_id', :value => @unit.id}
      %label Upload a file...
      %input{:type => 'file', :name => 'file'}
  .modal-footer
    %a{:href => '#', :class => 'btn btn-primary', :id => 'create_material_button'} Create
    %a{:href => '#', :class => 'btn', 'data-dismiss' => 'modal'} Cancel

#new_material_link.modal.hide.fade.in
  .modal-header
    %a.close{'data-dismiss' => 'modal'} x
    %h3 New Link:
  .modal-body
    = form_tag materials_path, :remote => true, :class => 'material_form_link', :id => 'material_form_link' do
      %label Name
      %input{:name => 'material[name]'}
      %label Link URL
      %input{:name => 'material[url]', :size => 200}
      %input{:type => 'hidden', :name => 'unit_id', :value => @unit.id}
  .modal-footer
    %a{:href => '#', :class => 'btn btn-primary', :id => 'create_material_link_button'} Create
    %a{:href => '#', :class => 'btn', 'data-dismiss' => 'modal'} Cancel

#edit_material.modal.hide.fade.in
  .modal-header
    %a.close{'data-dismiss' => 'modal'} x
    %h3 Edit the name for this material:
  .modal-body
    = form_tag materials_path, :remote => true, :multipart => true, :class => 'material_form', :id => 'rename_material_form' do
      %input{:name => 'material_name', :id => 'material_name'}
      %input{:type => 'hidden', :name => 'material_id', :id => 'rename_material_id'}
      %input{:type => 'hidden', :name => 'unit_id', :value => @unit.id}
  .modal-footer
    %a{:href => '#', :class => 'btn btn-primary', :id => 'rename_material_button'} Rename
    %a{:href => '#', :class => 'btn', 'data-dismiss' => 'modal'} Cancel