config/routes.rb
HortwithmshV2::Application.routes.draw do
  resources :subjects
  resources :hydroponics_data
  resources :materials

  resources :classrooms do
    post 'edit'
    post 'add_unit'
    post 'delete'
  end

  resources :materials do
    post 'delete'
    post 'edit_name'
  end

  resources :units do
    post 'delete'
  end

  match 'hydroponics_data/csv/:filter' => 'hydroponics_data#download'

  post 'classrooms/sort' => 'classrooms#sort'

  match 'classes/:name' => 'main#classroom'
  match 'classes/:class_name/files/:file_name' => 'main#download'

  match 'plant_science' => 'main#plant_science'
  match 'plant_science_ii' => 'main#plant_science_ii'
  match 'floral_design' => 'main#floral_design'
  match 'career_choices' => 'main#career_choices'

  match 'about' => 'main#about'
  match 'ffa' => 'main#ffa'
  match 'stem' => 'main#stem'
  match 'plant-sale' => 'main#plant_sale'

  match 'mobile' => 'mobile#index'
  post 'mobile/post-plant-data' => 'mobile#post_plant_data'
  post 'mobile/get-plant-information' => 'mobile#get_plant_information'

  root :to => 'main#index'

end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :unit

  default_scope order("sort asc")

  def save_file(options={})
    extension = options[:file].original_filename.match(/\.\w{3}/)[0]
    filename = "#{UUIDTools::UUID.timestamp_create().to_s}#{extension}"
    write_path = "#{Rails.root}/public/materials/#{filename}"

    File.open(write_path, 'wb') {|f| f.write options[:file].read}

    self.filename = filename
    self.save
  end

  def download_path(class_path)
    "/classes/#{class_path}/files/#{self.name_url}#{self.extension}"
  end

  def name_url
    self.name.gsub(' ','-')
  end

  def extension
    self.filename.match(/\.\w{3}/)[0]
  end

  def delete_file
    File.delete("#{Rails.root}/public/materials/#{filename}") if self.filename
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_filter :authenticate

  def create
    unit = Unit.find(params[:unit_id])

    new_material = Material.new(params[:material])
    
    new_material.save_file({:file => params[:file]}) if params[:file]
    new_material.url = params[:url] if params[:url]

    unit.materials << new_material
    materials = render_to_string(:partial => 'index_material', :collection => unit.materials)

    respond_to do |format|
      format.js { @results = {:message => 'New unit material added.', :materials => materials} }
    end
  end

  def delete
    material = Material.find(params[:material_id])
    unit = material.unit

    material.delete_file
    unit.materials.delete(material)
    materials_html = render_to_string(:partial => 'materials/index_material', :collection => unit.materials, :layout => false)

    respond_to do |format|
      format.js { @results = {:message => 'Unit updated, material removed.', :materials => materials_html} }
    end
  end

  def edit_name
    material = Material.find(params[:material_id])

    material.name = params[:material_name]
    material.save

    unit = Unit.find(params[:unit_id])

    materials_html = render_to_string(:partial => 'materials/index_material', :collection => unit.materials, :layout => false)

    respond_to do |format|
      format.js { @results = {:message => 'Unit material renamed.', :materials => materials_html} }
    end
  end
end

app/helpers/materials_helper.rb
module MaterialsHelper
  def helper_linked_name(material)
    return link_to material.name, get_valid_url(material.url) if !material.url.to_s.empty?
    return material.name
  end

  def get_valid_url(url)
    valid_protocols = [
      'http://',
      'ftp://',
      'https://'
    ]

    valid_protocols.each do |protocol|
      return url if url.include?(protocol)
    end

    return 'http://' + url;
  end
end

app/views/materials/_index_material.html.haml
.row.index_material{'data-id' => index_material.id}
  .span9.material_info
    %span 
      = helper_linked_name(index_material)
  .span3.actions
    %a.btn.edit-material{'data-toggle' => 'modal', :href => '#edit_material', 'data-id' => index_material.id, 'data-name' => index_material.name} Edit Name
    // %a.btn Disable
    = link_to('Delete', (material_path(index_material) + '/delete'), :remote => true, :method => 'post', :confirm => "Are you sure you want to delete #{index_material.name}?", :class => 'btn btn-danger')

app/views/materials/create.js.erb
Alert.show('<%=escape_javascript(@results[:message])%>');
$('#materials').html("<%= escape_javascript(raw(@results[:materials])) %>");
$('.modal').modal('hide');

app/views/materials/delete.js.erb
Alert.show('<%=escape_javascript(@results[:message])%>');
$('#materials').html($("<%=escape_javascript(raw(@results[:materials].strip))%>"));

app/views/materials/edit_name.js.erb
Alert.show('<%=escape_javascript(@results[:message])%>');
$('#materials').html($("<%=escape_javascript(raw(@results[:materials].strip))%>"));
$('.modal').modal('hide');
CMS.init();