config/routes.rb
HortwithmshV2::Application.routes.draw do
  resources :subjects
  resources :hydroponics_data
  resources :materials

  resources :classrooms do
    post 'edit'
    post 'add_unit'
    post 'delete'
  end

  resources :materials do
    post 'delete'
    post 'edit_name'
  end

  resources :units do
    post 'delete'
  end

  match 'hydroponics_data/csv/:filter' => 'hydroponics_data#download'

  post 'classrooms/sort' => 'classrooms#sort'

  match 'classes/:name' => 'main#classroom'
  match 'classes/:class_name/files/:file_name' => 'main#download'

  match 'plant_science' => 'main#plant_science'
  match 'plant_science_ii' => 'main#plant_science_ii'
  match 'floral_design' => 'main#floral_design'
  match 'career_choices' => 'main#career_choices'

  match 'about' => 'main#about'
  match 'ffa' => 'main#ffa'
  match 'stem' => 'main#stem'
  match 'plant-sale' => 'main#plant_sale'

  match 'mobile' => 'mobile#index'
  post 'mobile/post-plant-data' => 'mobile#post_plant_data'
  post 'mobile/get-plant-information' => 'mobile#get_plant_information'

  root :to => 'main#index'

end

app/views/layouts/application.html.haml
!!! html

%html
  %head
    %title= yield :title
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'http://www.google.com/jsapi'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    - if @meta_description
      %meta{:name => 'description', :content => @meta_description }

  %body{:onload => 'Page.init();'}
    = yield :head
    .container
      = yield :breadcrumbs
      .row
        .span3
          %ul.nav.nav-pills.nav-stacked
            =nav_link 'About Me', '/about'
            =nav_link 'FFA Plant Sale', '/plant-sale'
            =nav_link 'STEM Program', '/stem'
          %h3 Classes
          %ul.nav.nav-pills.nav-stacked
            - @classrooms.each do |classroom|
              =main_nav_link classroom.name, '/classes/' + classroom.name_url

          = render :partial => 'facebook_badge'

          -#
            %h3 Activities
            %ul.nav.nav-pills.nav-stacked
              %li.dropdown{:id => 'nav_ffa'}
                %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#nav_ffa'}
                  FFA
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to 'Current Members'
                  %li= link_to 'Competitions'
                  %li= link_to 'Evergreen State Fair'
              %li= link_to 'STEM', 'stem'
              %li= link_to 'Plant Sale', 'plant_sale'
              %li= link_to 'Our Greenhouse', 'greenhouse'
              %li= link_to 'Hydroponics', 'hydroponics'
        .span9
          = yield
  
  = render :partial => 'main/google_tracking'

app/views/layouts/application_old.html.haml
!!! html

%html
  %head
    %title Horticulture With Ms. H
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    .navbar
      .navbar-inner
        .container
          .brand
            Classes With Ms. H
          %ul.nav
            %li= link_to 'About Ms H.', 'about'
            %li= link_to 'FFA', 'ffa'
            %li= link_to 'STEM', 'stem'
            %li= link_to 'Plant Sale', 'plant_sale'
            %li= link_to 'Our Greenhouse', 'greenhouse'
            %li= link_to 'Hydroponics', 'hydroponics'
            %li
              %a Plant Science
            %li
              %a Plant Science II
            %li
              %a Floral Design
            %li
              %a Career Choices

    .container
      .row
        .span12
          = yield

app/views/layouts/classrooms.html.haml
!!! html

%html
  %head
    %title Manage - Horticulture With Ms. H
    = stylesheet_link_tag 'application_cms', :media => 'all'
    = javascript_include_tag 'application_cms'
    = csrf_meta_tags

  %body
    .container
      .navbar
        .navbar-inner
          = link_to 'Classroom Manager', classrooms_path, :class => 'brand'
          %ul.nav
            = nav_link('Classrooms', classrooms_path)
            = nav_link('Units', units_path)
            = nav_link('Hydroponics Data', hydroponics_data_path)
      .row
        .span12
          / %ul.breadcrumb
          /   %li
          /     = link_to 'Classrooms', classrooms_path
          /   = yield(:breadcrumb)
      .row
        .span12
          .alert.alert-success
            %span 
            %a.close{:href => '#'} &times;
      .row
        .span12
          = yield

app/views/layouts/mobile.html.haml
!!! html

%html
  %head
    %title Mobile Field Data Entry
    = stylesheet_link_tag 'application_mobile'
    = javascript_include_tag 'http://www.google.com/jsapi'
    = javascript_include_tag '//code.jquery.com/jquery-1.7.1.min.js'
    = javascript_include_tag 'mobile'
    = csrf_meta_tags
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1'}
    %meta{:name => 'apple-mobile-web-app-capable', :content => 'yes'}

  %body
    = yield
  
  = render :partial => 'main/google_tracking'